// Generated by Wrangler on Sun Apr 21 2024 22:07:54 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types`

interface Env {
	short_urls: KVNamespace;
	SECRET_KEY: string;
	DB: D1Database;
}
